# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20181018_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='local',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='responsavel',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
